### ISSUE TITLE
image hyperlink 

### ISSUE THREAD

**Issue by faxiang1230** [openthos/openthos.github.io#11]
我看到有些图片的位置都是引用的超链接，不如引用图片的相对位置，这样防止后面的项目迁移出现问题。
index.html->https://openthos.github.io/images/banner1.jpg

**Comment by faxiang1230** [comment]
纠正一下，index.html->https://openthos.github.io/images/banner1.jpg的数据是通过打开openthos.github.io的网页源码看到的，当我去看source的时候发现都是使用baseurl得到的；
也许不会导致问题，不过还是请确认一下.

**Comment by maqingqing** [comment]
好的。我会确认一下，如果需要会更改图片路径

**Comment by faxiang1230** [comment]
多谢。
我想知道是否有人提供最终的网站样式？最终长什么样是谁来决定？
如果有的话，能不能提供一下？
PS:最近有点时间,想要个人参与一下网站的设计,请多多包涵.

**Comment by maqingqing** [comment]
没有确定的样式。现在的内容是同刘总和刘老师一起讨论的结果，样式都是我写的。没有具体设计、如果您有需求和想法请告诉我

**Comment by faxiang1230** [comment]
我想要参与一下，因为不知道最终设计成什么样不知道怎么参与.
网站的文本内容你可以让其他人帮你填充一下，速度可以稍快一些。
我看了您今天的提交，样式又更改了

**Comment by maqingqing** [comment]
昨天刚提交的版本修改了banner，删减了一些内容。（之前的内容有点多）
现在的网站我这边结构基本已经完成了，里面需要的文字内容和一些文字说明需要工程师写好之后给我一份文档我才能填充。
